import { MediaType } from "../types/general";
import {
  ReviewerType,
  UserResponse,
  UserRole,
  UserStatus,
  AddressType,
} from "../types/user";

export const reviewersResponse: UserResponse[] = [
  {
    id: "12344",
    name: "Jens Jensen",
    email: "jens@jensen.test",
    role: UserRole.REVIEWER,
    status: UserStatus.ACTIVE,
    institutionName: " Test biblo",
    generalComment: "bla bla",
    firstName: "Jens",
    lastName: "Jensen",
    nameExtra: "",
    favoriteMediaType: MediaType.MOVIE,
    reviewerType: {
      [ReviewerType.CHILDREN]: true,
      [ReviewerType.ADULTS]: true,
      [ReviewerType.PUBLIC]: true,
      [ReviewerType.SCHOOL]: true,
    },
    subjectAreasOfInterest: [
      {
        id: "testA",
        description: "",
      },
      {
        id: "testB",
        description: "",
      },
    ],
    hasWriteAccess: true,
    payrollNumber: "63542",
    autobiography: "Jeg har et godt tilbud til dig",
    activeAddressType: AddressType.PRIVATE,
    privateAddress: {
      street: "Industrivejen 12",
      zip: "2312",
      city: "Rødovre",
      streetExtra: "",
      phone: "23423423",
      email: "asdas@2qwe.dk",
    },
    institutionAddress: {
      street: "Industrivejen 12",
      zip: "2312",
      city: "Rødovre",
      streetExtra: "",
      phone: "23423423",
      email: "asdas@2qwe.dk",
    },
  },
  {
    id: "12345",
    name: "Lars Larsen",
    email: "lars@larsen.test",
    role: UserRole.REVIEWER,
    status: UserStatus.ACTIVE,
    institutionName: " Test biblo",
    generalComment: "bla bla",
    firstName: "Lars",
    lastName: "Larsen",
    nameExtra: "",
    favoriteMediaType: MediaType.BOOK,
    reviewerType: {
      [ReviewerType.CHILDREN]: true,
      [ReviewerType.ADULTS]: false,
      [ReviewerType.PUBLIC]: true,
      [ReviewerType.SCHOOL]: false,
    },
    subjectAreasOfInterest: [
      {
        id: "testA",
        description: "Kun 3 om året af den slags",
      },
      {
        id: "testB",
        description: "Så mange som muligt af dem her",
      },
      {
        id: "testC",
        description: "",
      },
      {
        id: "testD",
        description: "",
      },
    ],
    hasWriteAccess: true,
    payrollNumber: "1231212",
    autobiography: "Jeg har et godt tilbud til dig",
    activeAddressType: AddressType.PRIVATE,
    privateAddress: {
      street: "Industrivejen 12",
      zip: "2312",
      city: "Rødovre",
      streetExtra: "",
      phone: "23423423",
      email: "asdas@2qwe.dk",
    },
    institutionAddress: {
      street: "Industrivejen 12",
      zip: "2312",
      city: "Rødovre",
      streetExtra: "",
      phone: "23423423",
      email: "asdas@2qwe.dk",
    },
  },
  {
    id: "12346",
    name: "Peter Petersen",
    email: "peter@petersen.test",
    role: UserRole.REVIEWER,
    status: UserStatus.ACTIVE,
    institutionName: " Test biblo",
    generalComment: "bla bla",
    firstName: "Peter",
    lastName: "Petersen",
    nameExtra: "",
    favoriteMediaType: MediaType.BOOK,
    reviewerType: {
      [ReviewerType.CHILDREN]: true,
      [ReviewerType.ADULTS]: true,
      [ReviewerType.PUBLIC]: true,
      [ReviewerType.SCHOOL]: true,
    },
    subjectAreasOfInterest: [
      {
        id: "testC",
        description: "",
      },
      {
        id: "testD",
        description: "Kun til nøds",
      },
    ],
    hasWriteAccess: true,
    payrollNumber: "123121212",
    autobiography: "Jeg har et godt tilbud til dig",
    activeAddressType: AddressType.PRIVATE,
    privateAddress: {
      street: "Industrivejen 12",
      zip: "2312",
      city: "Rødovre",
      streetExtra: "",
      phone: "23423423",
      email: "asdas@2qwe.dk",
    },
    institutionAddress: {
      street: "Industrivejen 12",
      zip: "2312",
      city: "Rødovre",
      streetExtra: "",
      phone: "23423423",
      email: "asdas@2qwe.dk",
    },
  },
  {
    id: "12347",
    name: "Hans Hansen",
    email: "hans@hansen.test",
    role: UserRole.REVIEWER,
    status: UserStatus.ACTIVE,
    institutionName: " Test biblo",
    generalComment: "bla bla",
    firstName: "Hans",
    lastName: "Hansen",
    nameExtra: "",
    favoriteMediaType: MediaType.BOOK,
    reviewerType: {
      [ReviewerType.CHILDREN]: false,
      [ReviewerType.ADULTS]: true,
      [ReviewerType.PUBLIC]: true,
      [ReviewerType.SCHOOL]: false,
    },
    subjectAreasOfInterest: [
      {
        id: "testB",
        description: "Så mange som muligt af dem her",
      },
      {
        id: "testC",
        description: "",
      },
      {
        id: "testD",
        description: "",
      },
    ],
    hasWriteAccess: true,
    payrollNumber: "1231211232",
    autobiography: "Jeg har et godt tilbud til dig",
    activeAddressType: AddressType.PRIVATE,
    privateAddress: {
      street: "Industrivejen 12",
      zip: "2312",
      city: "Rødovre",
      streetExtra: "",
      phone: "23423423",
      email: "asdas@2qwe.dk",
    },
    institutionAddress: {
      street: "Industrivejen 12",
      zip: "2312",
      city: "Rødovre",
      streetExtra: "",
      phone: "23423423",
      email: "asdas@2qwe.dk",
    },
  },
  {
    id: "12348",
    name: "Lise Lisesen",
    email: "lise@lisesen.test",
    role: UserRole.REVIEWER,
    status: UserStatus.ACTIVE,
    institutionName: " Test biblo",
    generalComment: "bla bla",
    firstName: "Lise",
    lastName: "Lisesen",
    nameExtra: "",
    favoriteMediaType: MediaType.MULTIMEDIA,
    reviewerType: {
      [ReviewerType.CHILDREN]: true,
      [ReviewerType.ADULTS]: false,
      [ReviewerType.PUBLIC]: true,
      [ReviewerType.SCHOOL]: true,
    },
    subjectAreasOfInterest: [
      {
        id: "testC",
        description: "",
      },
      {
        id: "testD",
        description: "",
      },
    ],
    hasWriteAccess: true,
    payrollNumber: "12sss31212",
    autobiography: "Jeg har et godt tilbud til dig",
    activeAddressType: AddressType.PRIVATE,
    privateAddress: {
      street: "Industrivejen 12",
      zip: "2312",
      city: "Rødovre",
      streetExtra: "",
      phone: "23423423",
      email: "asdas@2qwe.dk",
    },
    institutionAddress: {
      street: "Industrivejen 12",
      zip: "2312",
      city: "Rødovre",
      streetExtra: "",
      phone: "23423423",
      email: "asdas@2qwe.dk",
    },
  },
  {
    id: "12349",
    name: "Jesper Jespersen",
    email: "jesper@jespersen.test",
    role: UserRole.REVIEWER,
    status: UserStatus.ACTIVE,
    institutionName: " Test biblo",
    generalComment: "bla bla",
    firstName: "Jesper",
    lastName: "Jespersen",
    nameExtra: "",
    favoriteMediaType: MediaType.BOOK,
    reviewerType: {
      [ReviewerType.CHILDREN]: true,
      [ReviewerType.ADULTS]: true,
      [ReviewerType.PUBLIC]: true,
      [ReviewerType.SCHOOL]: false,
    },
    subjectAreasOfInterest: [
      {
        id: "testA",
        description: "",
      },
      {
        id: "testB",
        description: "Kun hver tredje søndag i ulige måneder",
      },
      {
        id: "testC",
        description: "",
      },
    ],
    hasWriteAccess: true,
    payrollNumber: "1231212342",
    autobiography: "Jeg har et godt tilbud til dig",
    activeAddressType: AddressType.PRIVATE,
    privateAddress: {
      street: "Industrivejen 12",
      zip: "2312",
      city: "Rødovre",
      streetExtra: "",
      phone: "23423423",
      email: "asdas@2qwe.dk",
    },
    institutionAddress: {
      street: "Industrivejen 12",
      zip: "2312",
      city: "Rødovre",
      streetExtra: "",
      phone: "23423423",
      email: "asdas@2qwe.dk",
    },
  },
  {
    id: "12350",
    name: "Bendt Bendtsen",
    email: "bendt@bendtsen.test",
    role: UserRole.REVIEWER,
    status: UserStatus.ACTIVE,
    institutionName: " Test biblo",
    generalComment: "bla bla",
    firstName: "Bendt",
    lastName: "Bendtsen",
    nameExtra: "",
    favoriteMediaType: MediaType.BOOK,
    reviewerType: {
      [ReviewerType.CHILDREN]: false,
      [ReviewerType.ADULTS]: false,
      [ReviewerType.PUBLIC]: true,
      [ReviewerType.SCHOOL]: false,
    },
    subjectAreasOfInterest: [
      {
        id: "testA",
        description: "Kun 3 om året af den slags",
      },
      {
        id: "testC",
        description: "",
      },
      {
        id: "testD",
        description: "",
      },
    ],
    hasWriteAccess: true,
    payrollNumber: "1231212",
    autobiography: "Jeg har et godt tilbud til dig",
    activeAddressType: AddressType.PRIVATE,
    privateAddress: {
      street: "Industrivejen 12",
      zip: "2312",
      city: "Rødovre",
      streetExtra: "",
      phone: "23423423",
      email: "asdas@2qwe.dk",
    },
    institutionAddress: {
      street: "Industrivejen 12",
      zip: "2312",
      city: "Rødovre",
      streetExtra: "",
      phone: "23423423",
      email: "asdas@2qwe.dk",
    },
  },
  {
    id: "12351",
    name: "Karsten Karstensen",
    email: "karsten@karstensen.test",
    role: UserRole.REVIEWER,
    status: UserStatus.ACTIVE,
    institutionName: " Test biblo",
    generalComment: "bla bla",
    firstName: "Karsten",
    lastName: "Karstensen",
    nameExtra: "",
    favoriteMediaType: MediaType.BOOK,
    reviewerType: {
      [ReviewerType.CHILDREN]: true,
      [ReviewerType.ADULTS]: false,
      [ReviewerType.PUBLIC]: true,
      [ReviewerType.SCHOOL]: true,
    },
    subjectAreasOfInterest: [
      {
        id: "testB",
        description: "Så mange som muligt af dem her",
      },
      {
        id: "testC",
        description: "",
      },
    ],
    hasWriteAccess: true,
    payrollNumber: "1231212321",
    autobiography: "Jeg har et godt tilbud til dig",
    activeAddressType: AddressType.PRIVATE,
    privateAddress: {
      street: "Industrivejen 12",
      zip: "2312",
      city: "Rødovre",
      streetExtra: "",
      phone: "23423423",
      email: "asdas@2qwe.dk",
    },
    institutionAddress: {
      street: "Industrivejen 12",
      zip: "2312",
      city: "Rødovre",
      streetExtra: "",
      phone: "23423423",
      email: "asdas@2qwe.dk",
    },
  },
  {
    id: "12352",
    name: "Mona Monasen",
    email: "mona@monasen.test",
    role: UserRole.REVIEWER,
    status: UserStatus.ACTIVE,
    institutionName: " Test biblo",
    generalComment: "bla bla",
    firstName: "Mona",
    lastName: "Mona",
    nameExtra: "",
    favoriteMediaType: MediaType.EBOOK,
    reviewerType: {
      [ReviewerType.CHILDREN]: true,
      [ReviewerType.ADULTS]: true,
      [ReviewerType.PUBLIC]: true,
      [ReviewerType.SCHOOL]: true,
    },
    subjectAreasOfInterest: [
      {
        id: "testC",
        description: "",
      },
    ],
    hasWriteAccess: true,
    payrollNumber: "1231223412",
    autobiography: "Jeg har et godt tilbud til dig",
    activeAddressType: AddressType.PRIVATE,
    privateAddress: {
      street: "Industrivejen 12",
      zip: "2312",
      city: "Rødovre",
      streetExtra: "",
      phone: "23423423",
      email: "asdas@2qwe.dk",
    },
    institutionAddress: {
      street: "Industrivejen 12",
      zip: "2312",
      city: "Rødovre",
      streetExtra: "",
      phone: "23423423",
      email: "asdas@2qwe.dk",
    },
  },
  {
    id: "12353",
    name: "Ole Olesen",
    email: "ole@olesen.test",
    role: UserRole.REVIEWER,
    status: UserStatus.ACTIVE,
    institutionName: " Test biblo",
    generalComment: "bla bla",
    firstName: "Ole",
    lastName: "Olesen",
    nameExtra: "",
    favoriteMediaType: MediaType.BOOK,
    reviewerType: {
      [ReviewerType.CHILDREN]: true,
      [ReviewerType.ADULTS]: false,
      [ReviewerType.PUBLIC]: false,
      [ReviewerType.SCHOOL]: false,
    },
    subjectAreasOfInterest: [
      {
        id: "testA",
        description: "",
      },
      {
        id: "testB",
        description: "Så mange som muligt af dem her",
      },
      {
        id: "testC",
        description: "",
      },
      {
        id: "testD",
        description: "",
      },
    ],
    hasWriteAccess: true,
    payrollNumber: "12311231212",
    autobiography: "Jeg har et godt tilbud til dig",
    activeAddressType: AddressType.PRIVATE,
    privateAddress: {
      street: "Industrivejen 12",
      zip: "2312",
      city: "Rødovre",
      streetExtra: "",
      phone: "23423423",
      email: "asdas@2qwe.dk",
    },
    institutionAddress: {
      street: "Industrivejen 12",
      zip: "2312",
      city: "Rødovre",
      streetExtra: "",
      phone: "23423423",
      email: "asdas@2qwe.dk",
    },
  },
  {
    id: "12354",
    name: "Poul Poulsen",
    email: "poul@poulsen.test",
    role: UserRole.REVIEWER,
    status: UserStatus.ACTIVE,
    institutionName: " Test biblo",
    generalComment: "bla bla",
    firstName: "Poul",
    lastName: "Poulsen",
    nameExtra: "",
    favoriteMediaType: MediaType.BOOK,
    reviewerType: {
      [ReviewerType.CHILDREN]: true,
      [ReviewerType.ADULTS]: false,
      [ReviewerType.PUBLIC]: true,
      [ReviewerType.SCHOOL]: false,
    },
    subjectAreasOfInterest: [
      {
        id: "testA",
        description: "Kun 3 om året af den slags",
      },
      {
        id: "testB",
        description: "Så mange som muligt af dem her",
      },
      {
        id: "testD",
        description: "",
      },
    ],
    hasWriteAccess: true,
    payrollNumber: "123121123122",
    autobiography: "Jeg har et godt tilbud til dig",
    activeAddressType: AddressType.PRIVATE,
    privateAddress: {
      street: "Industrivejen 12",
      zip: "2312",
      city: "Rødovre",
      streetExtra: "",
      phone: "23423423",
      email: "asdas@2qwe.dk",
    },
    institutionAddress: {
      street: "Industrivejen 12",
      zip: "2312",
      city: "Rødovre",
      streetExtra: "",
      phone: "23423423",
      email: "asdas@2qwe.dk",
    },
  },
];
